### ISSUE TITLE
.

### ISSUE THREAD

**Issue by jeffreyhanna** [norio-nomura/docker-sourcekit-builder#4]

**Comment by jeffreyhanna** [comment]
.

**Comment by norio-nomura** [comment]
> `docker build -t sourcekit-builder:302_14_04 https://github.com/jeffreyhanna/docker-sourcekit-builder.git`

This builds image from `master` branch of your repository.
You need to specify your `302_14_04` branch as documented in [docker build - Docker Documentation](https://docs.docker.com/engine/reference/commandline/build/#git-repositories) instead of `master`.
`docker build -t sourcekit-builder:302_14_04 https://github.com/jeffreyhanna/docker-sourcekit-builder.git#302_14_04`
Other steps looks good to me.
